/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.CentreDistributionRole;

import Business.EcoSystem;
import Business.Enterprise.CDCEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PHDEnterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ProviderWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.PHDRole.ProcessRequestJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanil
 */
public class CentreDistributionWorkAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    EcoSystem business;
    Network n;
    UserAccount userAccount;
    Enterprise enterprise;

    /**
     * Creates new form CentreDistributionWorkAreaJPanel
     */
    public CentreDistributionWorkAreaJPanel(JPanel userProcessContainer,Enterprise enterprise,EcoSystem business,Network n,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        this.n=n;
        this.userAccount=userAccount;
        this.enterprise=enterprise;
        populateTable();

    }
     private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) finaljTable1.getModel();

        model.setRowCount(0);
        for (Network n : business.getNetworkList()){
            for (Enterprise enterprise : n.getEnterpriseDirectory().getEnterpriseList()){
               
                  if (enterprise instanceof CDCEnterprise){
                    for (WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()) {
                   
            Object[] row = new Object[4];
            row[0] = request;
           // row[] = request.getSender().getEmployee().getName();
            row[1] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[2]=  ((ProviderWorkRequest)request).getOrder();
            row[3] = request.getStatus();
                        
            model.addRow(row);
            }  
                  
             
        }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        finaljTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        finaljTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Receiver", "Order", "Status"
            }
        ));
        jScrollPane1.setViewportView(finaljTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 104, 375, 124));

        jButton1.setText("Assign to me");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 246, 111, -1));

        jButton2.setText("Forward to Sites");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 303, -1, -1));

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 int selectedRow = finaljTable1.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }
        // UserAccount userAccount = null;
        WorkRequest request = (WorkRequest) finaljTable1.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("Pending");
        populateTable();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  int selectedRow = finaljTable1.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        ProviderWorkRequest request1 = (ProviderWorkRequest) finaljTable1.getValueAt(selectedRow, 0);

        request1.setStatus("Processing");
        
        FinalProcessRequestJPanel processCustomerWorkRequest = new FinalProcessRequestJPanel(userProcessContainer, request1);
        userProcessContainer.add("processWorkRequestJPanel", processCustomerWorkRequest);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);// TODO add your        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
populateTable();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable finaljTable1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
