/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.CentreDistributionRole;

import Business.WorkQueue.ProviderWorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sanil
 */
public class FinalProcessRequestJPanel extends javax.swing.JPanel {
 JPanel userProcessContainer;
    ProviderWorkRequest request1;
    /**
     * Creates new form FinalProcessRequestJPanel
     */
    public FinalProcessRequestJPanel(JPanel userProcessContainer,ProviderWorkRequest request1) {
        initComponents();
         this.userProcessContainer=userProcessContainer;
        this.request1=request1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitjButton1 = new javax.swing.JButton();
        finaljTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitjButton1.setText("Submit");
        submitjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButton1ActionPerformed(evt);
            }
        });
        add(submitjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));
        add(finaljTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 93, -1));

        jLabel1.setText("Signature");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButton1ActionPerformed
  if (finaljTextField1.getText().isEmpty()) {
             JOptionPane.showMessageDialog(null,"enter your Signature");
             return;
        }
        
        
        
        request1.setOrderApproved(finaljTextField1.getText());
        request1.setStatus("Shipped to Sites");        // TODO add your handling code here:
    }//GEN-LAST:event_submitjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField finaljTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton submitjButton1;
    // End of variables declaration//GEN-END:variables
}
