/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.ProviderRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SiteDirectoryEnterprise;
import Business.Network.Network;
import Business.Organization.ProviderOrganization;
import Business.Patient;
import Business.ProductVaccine;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanil
 */
public class CreateNewPatientJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    EcoSystem business;
    Network n;
    UserAccount userAccount;
    Enterprise enterprise;
    ProviderOrganization providerOrganization;

    /**
     * Creates new form CreateNewPatientJPanel
     */
    public CreateNewPatientJPanel(JPanel userProcessContainer,EcoSystem business,Enterprise enterprise,UserAccount userAccount,Network n,ProviderOrganization providerOrganization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        this.n=n;
        this.userAccount=userAccount;
        this.providerOrganization=providerOrganization;
       // populateTable();

    }
    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)insurancejTable.getModel();
                
        dtm.setRowCount(0);
        
            for (Patient pa : providerOrganization.getPatientDir().getPatientDir()){
                
                Object row[] = new Object[3];
            row[0] = pa;
            row[1] = pa.getInsuranceNo();
            row[2] = pa.getInsuranceStatus();
            dtm.addRow(row);
            }
                
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        patientjTextField1 = new javax.swing.JTextField();
        InsuranceNojTextField2 = new javax.swing.JTextField();
        cmbInsuranceType = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        insurancejTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Patient Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jLabel2.setText("Insurance No");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel3.setText("InsuranceStatus");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));
        add(patientjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 80, -1));
        add(InsuranceNojTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 80, -1));

        cmbInsuranceType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Insurance", "Under-Insured", "Private Insurance" }));
        add(cmbInsuranceType, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 80, -1));

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        insurancejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Insurance No", "Insurance Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(insurancejTable);
        if (insurancejTable.getColumnModel().getColumnCount() > 0) {
            insurancejTable.getColumnModel().getColumn(1).setResizable(false);
            insurancejTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String name = patientjTextField1.getText();
 int insuranceNo = Integer.parseInt(InsuranceNojTextField2.getText());
 String insuranceStatus =String.valueOf(cmbInsuranceType.getSelectedItem());
 Patient patient = (Patient)providerOrganization.getPatientDir().addPatient();
 patient.setName(patientjTextField1.getText());
patient.setInsuranceStatus(insuranceStatus);
patient.setInsuranceNo(insuranceNo);
//providerOrganization.getPatientDir().addPatient();
populateTable();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InsuranceNojTextField2;
    private javax.swing.JComboBox cmbInsuranceType;
    private javax.swing.JTable insurancejTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField patientjTextField1;
    // End of variables declaration//GEN-END:variables
}
