/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.ProviderRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SiteDirectoryEnterprise;
import Business.Network.Network;
import Business.Organization.ProviderOrganization;
import Business.UserAccount.UserAccount;


import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import static java.time.Clock.system;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanil
 */
public class ProviderWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private ProviderOrganization providerOrganization;
    private EcoSystem business;
    private Network n;
    
    

    /**
     * Creates new form ProviderWorkAreaJPanel
     */
    public ProviderWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,ProviderOrganization providerOrganization,Enterprise enterprise,EcoSystem business,Network n) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.providerOrganization = providerOrganization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business=business;
        this.n=n;
        
//        populateRequestTable();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BrowseProductCatalogjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("                            Provider Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 370, 34));

        BrowseProductCatalogjButton.setText("Browse Product Catalog");
        BrowseProductCatalogjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseProductCatalogjButtonActionPerformed(evt);
            }
        });
        add(BrowseProductCatalogjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 298, -1));

        jButton1.setText("Create Patient");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 290, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BrowseProductCatalogjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseProductCatalogjButtonActionPerformed
BrowseProductCatalogJPanel bpjp = new BrowseProductCatalogJPanel(userProcessContainer,business,enterprise,userAccount,n);
      userProcessContainer.add("BrowseProduct", bpjp);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_BrowseProductCatalogjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      CreateNewPatientJPanel bpjp = new CreateNewPatientJPanel(userProcessContainer,business,enterprise,userAccount,n,providerOrganization);
      userProcessContainer.add("BrowseProduct", bpjp);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowseProductCatalogjButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
