/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.ProviderRole;

import Business.OrderItem;
import javax.swing.JPanel;

/**
 *
 * @author sanil
 */
public class ViewProductDetailsJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    OrderItem orderItem;

    /**
     * Creates new form ViewProductDetailsJPanel
     */
    public ViewProductDetailsJPanel(JPanel userProcessContainer,OrderItem orderItem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.orderItem=orderItem;
        
        
        
        
        String name  = orderItem.getProductvaccine().getProdName();
        int price = orderItem.getProductvaccine().getPrice();
        int availability = orderItem.getProductvaccine().getAvail();
        int id = orderItem.getProductvaccine().getProductId();
        txtProductName.setText(name);
        txtAvail.setText(String.valueOf(availability));
        txtProductPrice.setText(String.valueOf(price));
        txtProductId.setText(String.valueOf(id));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        productIDJLabel = new javax.swing.JLabel();
        productPriceJLabel = new javax.swing.JLabel();
        availabilityJLabel = new javax.swing.JLabel();
        txtAvail = new javax.swing.JTextField();
        txtProductPrice = new javax.swing.JTextField();
        txtProductId = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 455, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("View Product Details");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 23, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Product Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 91, -1, -1));

        productIDJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productIDJLabel.setText("Product ID");
        add(productIDJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 143, -1, -1));

        productPriceJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productPriceJLabel.setText("Product Price");
        add(productPriceJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 200, -1, -1));

        availabilityJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        availabilityJLabel.setText("Availability");
        add(availabilityJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 246, -1, -1));
        add(txtAvail, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 256, 114, -1));
        add(txtProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 200, 114, -1));

        txtProductId.setEnabled(false);
        add(txtProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 147, 114, -1));
        add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 95, 114, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availabilityJLabel;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel productIDJLabel;
    private javax.swing.JLabel productPriceJLabel;
    private javax.swing.JTextField txtAvail;
    private javax.swing.JTextField txtProductId;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductPrice;
    // End of variables declaration//GEN-END:variables
}
