/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PHDRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PHDEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;

import Business.WorkQueue.WorkRequest;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanil
 */
public class PHDWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem business;
    private Enterprise enterprise;
    //private PHDEnterprise phdEnterprise;
    
    private Network n;
    private UserAccount userAccount;
    

    /**
     * Creates new form PHDWorkAreaJPanel
     */
    public PHDWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise,EcoSystem business,Network n,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.business= business;
        this.n=n;
        this.userAccount=userAccount;
        
        
       
//        System.out.println("yy"+phdEnterprise.getName());
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addSitesjButton = new javax.swing.JButton();
        ManageRequestsjButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel1.setText("PHD Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 287, 30));

        addSitesjButton.setText("Add Sites");
        addSitesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSitesjButtonActionPerformed(evt);
            }
        });
        add(addSitesjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, 197, -1));

        ManageRequestsjButton1.setText("Manage Request");
        ManageRequestsjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageRequestsjButton1ActionPerformed(evt);
            }
        });
        add(ManageRequestsjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 79, 197, -1));

        jButton1.setText("View Bill From CDC");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 288, 197, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addSitesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSitesjButtonActionPerformed
 AddSitesJPanel mmajp = new AddSitesJPanel(userProcessContainer,business,n,enterprise,(PHDEnterprise)enterprise);
        userProcessContainer.add("AddSitesJPanel", mmajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);           // TODO add your handling code here:
    }//GEN-LAST:event_addSitesjButtonActionPerformed

    private void ManageRequestsjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageRequestsjButton1ActionPerformed
        ManageProviderWorkRequestJPanel mmajp = new ManageProviderWorkRequestJPanel(userProcessContainer,enterprise,business,n,userAccount);
        userProcessContainer.add("ManageRequests", mmajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);           // TODO add your handling code here:
    }//GEN-LAST:event_ManageRequestsjButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    distriBillFromCDCJPanel mmajp = new distriBillFromCDCJPanel(userProcessContainer,enterprise,business,n,userAccount);
        userProcessContainer.add("ManageBill", mmajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageRequestsjButton1;
    private javax.swing.JButton addSitesjButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
