/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PHDRole;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.ProviderWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sanil
 */
public class ProcessRequestJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    ProviderWorkRequest request1;
    UserAccount userAccount;

    /**
     * Creates new form ProcessRequestJPanel
     */
    public ProcessRequestJPanel(JPanel userProcessContainer,ProviderWorkRequest request1) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.request1=request1;
        this.userAccount=userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        submitjButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        resultjTextField = new javax.swing.JTextField();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 220, -1, -1));

        submitjButton2.setText("Submit");
        submitjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButton2ActionPerformed(evt);
            }
        });
        add(submitjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 220, -1, -1));

        jLabel1.setText("Signature");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 45, -1, -1));
        add(resultjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 42, 111, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButton2ActionPerformed
 if (resultjTextField.getText().isEmpty()) {
             JOptionPane.showMessageDialog(null,"enter your Signature");
             return;
        }
        
        
        request1.setOrderApproved(resultjTextField.getText());
        request1.setStatus("Sent to CDC");        // TODO add your handling code here:
    }//GEN-LAST:event_submitjButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField resultjTextField;
    private javax.swing.JButton submitjButton2;
    // End of variables declaration//GEN-END:variables
}
